<?php
if (!defined('_VALID_MOS') && !defined('_JEXEC')) die('Direct Access to ' . basename(__FILE__) . ' is not allowed.');
/**
*
* @package VehicleManager
* @copyright 2020 by Ordasoft
* @author Andrey Kvasnevskiy - OrdaSoft (akbet@mail.ru); Rob de Cleen (rob@decleen.com);
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
* Homepage: https://ordasoft.com/
*
* */
// Do not edit this file. Generated by admin script.
// VehicleManager Configuration file
// General Informations 
$vehiclemanager_configuration['release']['version']='5.6.1 Free';
$vehiclemanager_configuration['release']['date']='December 2020';
// edit vehicle 
$vehiclemanager_configuration['editvehicle']['default']['lang']='';
// price settings
$vehiclemanager_configuration['price']['show']='1';
$vehiclemanager_configuration['price']['string']='1';
$vehiclemanager_configuration['price']['registrationlevel']='-2';
// auto increment for vehicleid, if 1 - can't add random vehicleid 
$vehiclemanager_configuration['vehicleid']['auto-increment']['boolean']='0';
// review settings
$vehiclemanager_configuration['reviews']['show']='1';
$vehiclemanager_configuration['reviews']['registrationlevel']='-2';
// show contacts
$vehiclemanager_configuration['Contacts']['show']='1';
$vehiclemanager_configuration ['contacts']['registrationlevel']='-2';
// show cb_myvehicle
$vehiclemanager_configuration['cb_myvehicle']['show']='0';
$vehiclemanager_configuration['cb_myvehicle']['registrationlevel']='';
// show cb_edit
$vehiclemanager_configuration['cb_edit']['show']='0';
$vehiclemanager_configuration['cb_edit']['registrationlevel']='';
// show cb_rent
$vehiclemanager_configuration['cb_rent']['show']='0';
$vehiclemanager_configuration['cb_rent']['registrationlevel']='';
// show cb_buy
$vehiclemanager_configuration['cb_buy']['show']='0';
$vehiclemanager_configuration['cb_buy']['registrationlevel']='';
// show cb_history
$vehiclemanager_configuration['cb_history']['show']='0';
$vehiclemanager_configuration['cb_history']['registrationlevel']='';
// show Location
$vehiclemanager_configuration['Location_vehicle']['show']='1';
$vehiclemanager_configuration ['Location_vehicle']['registrationlevel']='-2';
$vehiclemanager_configuration['Reviews_vehicle']['show']='1';
$vehiclemanager_configuration ['Reviews_vehicle']['registrationlevel'] ='-2';
// rent settings
$vehiclemanager_configuration['rentstatus']['show']='1';
$vehiclemanager_configuration['rentrequest']['registrationlevel']='-2';
// buy settings
$vehiclemanager_configuration['buystatus']['show']='1';
$vehiclemanager_configuration['buyrequest']['registrationlevel']='-2';
// payment buy settings
$vehiclemanager_configuration['payment_buy_status']['show']='0';
$vehiclemanager_configuration['payment_buy']['registrationlevel']='8';
$vehiclemanager_configuration['pay_pal_buy']['business']='';
$vehiclemanager_configuration['pay_pal_buy']['return']='';
$vehiclemanager_configuration['pay_pal_buy']['image_url']='';
$vehiclemanager_configuration['pay_pal_buy']['cancel_return']='0';
//user manager
$vehiclemanager_configuration['user_manager_vm']['-2']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['-2']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['1']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['1']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['6']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['6']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['7']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['7']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['2']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['2']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['3']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['3']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['4']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['4']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['5']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['5']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['8']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['8']['count_foto']='5';
$vehiclemanager_configuration['user_manager_vm']['9']['count_car']='999';
$vehiclemanager_configuration['user_manager_vm']['9']['count_foto']='5';
// paypal rent settings
$vehiclemanager_configuration['payment_rent_status']['show']='0';
$vehiclemanager_configuration['payment_rent']['registrationlevel']='8';
$vehiclemanager_configuration['pay_pal_rent']['business']='';
$vehiclemanager_configuration['pay_pal_rent']['return']='';
$vehiclemanager_configuration['pay_pal_rent']['image_url']='';
$vehiclemanager_configuration['pay_pal_rent']['cancel_return']='';
$vehiclemanager_configuration['payment_real_or_test']['show']='0';
$vehiclemanager_configuration['special_price']['show']='0';
$vehiclemanager_configuration['google_captcha']['show']='0';
// edoc settings
$vehiclemanager_configuration['videos_tracks']['show']='1';
$vehiclemanager_configuration['edocs']['allow']='1';
$vehiclemanager_configuration['edocs']['show']='1';
$vehiclemanager_configuration['edocs']['registrationlevel']='-2';
$vehiclemanager_configuration['edocs']['location']='/components/com_vehiclemanager/edocs/';
$vehiclemanager_configuration['videos']['location']='/components/com_vehiclemanager/media/video/';
$vehiclemanager_configuration['tracks']['location']='/components/com_vehiclemanager/media/track/';
// debuging
$vehiclemanager_configuration['debug']='';
$vehiclemanager_configuration['page']['items']='6';
// foto size
$vehiclemanager_configuration['thumb_param']['show']= '1';
$vehiclemanager_configuration['foto']['high']= '200';
$vehiclemanager_configuration['foto']['width']= '200';
$vehiclemanager_configuration['fotomain']['high']= '1200';
$vehiclemanager_configuration['fotomain']['width']= '2800';
$vehiclemanager_configuration['fotogallery']['high']= '200';
$vehiclemanager_configuration['fotogallery']['width']= '369';
$vehiclemanager_configuration['fotogal']['high']= '100';
$vehiclemanager_configuration['fotogal']['width']= '100';
$vehiclemanager_configuration['fotoupload']['high']= '600';
$vehiclemanager_configuration['fotoupload']['width']= '1400';
$vehiclemanager_configuration['rotate_img']='1';
$vehiclemanager_configuration['license']['show']='0';
$vehiclemanager_configuration['license']['text']= '<p>Untitled document</p>
<p>License text</p>';
$vehiclemanager_configuration['option_edit']['show']='0';
$vehiclemanager_configuration['option_edit']['registrationlevel']='';
// button '[ Add vehicle ]'
$vehiclemanager_configuration['add_vehicle']['show']='0';
$vehiclemanager_configuration['add_vehicle']['registrationlevel']='';
// button '[ print PDF ]'
$vehiclemanager_configuration['print_pdf']['show']='0';
$vehiclemanager_configuration['print_pdf']['registrationlevel']='8';
// button '[ print View ]'
$vehiclemanager_configuration['print_view']['show']='0';
$vehiclemanager_configuration['print_view']['registrationlevel']='8';
// button '[ mail_to ]'
$vehiclemanager_configuration['mail_to']['show']='0';
$vehiclemanager_configuration['mail_to']['registrationlevel']='8';
// send email for admin
$vehiclemanager_configuration['addvehicle_email']['address']='';
$vehiclemanager_configuration['addvehicle_email']['show']='0';
$vehiclemanager_configuration['addvehicle_email']['registrationlevel']='';
$vehiclemanager_configuration['review_email']['address']='';
$vehiclemanager_configuration['review_added_email']['show']='0';
$vehiclemanager_configuration['review_added_email']['registrationlevel']='';
$vehiclemanager_configuration['rentrequest_email']['address']='';
$vehiclemanager_configuration['rentrequest_email']['show']='0';
$vehiclemanager_configuration['rentrequest_email']['registrationlevel']='';
$vehiclemanager_configuration['buyingrequest_email']['address']='';
$vehiclemanager_configuration['buyingrequest_email']['show']='0';
$vehiclemanager_configuration['buyingrequest_email']['registrationlevel']='';
// show in category picture
$vehiclemanager_configuration['cat_pic']['show']='1';
$vehiclemanager_configuration['approve_review']['show']='0';
$vehiclemanager_configuration['approve_review']['registrationlevel']='-2';
// show subcategory
$vehiclemanager_configuration['subcategory']['show']='1';
// show single subcategory
$vehiclemanager_configuration['single_subcategory_show']['show']='1';
$vehiclemanager_configuration['approve_on_add']['show']='1';
$vehiclemanager_configuration['approve_on_add']['registrationlevel']='-2';
$vehiclemanager_configuration['publish_on_add']['show']='1';
$vehiclemanager_configuration['publish_on_add']['registrationlevel']='-2';
//all_categories
$vehiclemanager_configuration['all_categories']='';
//view type
$vehiclemanager_configuration['view_type']='';
//view_vehicle
$vehiclemanager_configuration['view_vehicle']='';
//show_search_vehicle
$vehiclemanager_configuration['show_search_vehicle']='advanced';
//all_vehicle_layout
$vehiclemanager_configuration['all_vehicle_layout']='';
//show location map
$vehiclemanager_configuration['location_map']='1';
//manager_feature_image
$vehiclemanager_configuration['manager_feature_image']='1';
//manager_feature_category
$vehiclemanager_configuration['manager_feature_category']='1';
//sale_separator
$vehiclemanager_configuration['sale_separator']='1';
//extra1
$vehiclemanager_configuration['extra1']='0';
//extra2
$vehiclemanager_configuration['extra2']='0';
//extra3
$vehiclemanager_configuration['extra3']='0';
//extra4
$vehiclemanager_configuration['extra4']='0';
//extra5
$vehiclemanager_configuration['extra5']='0';
//extra6
$vehiclemanager_configuration['extra6']='0';
//extra7
$vehiclemanager_configuration['extra7']='0';
//extra8
$vehiclemanager_configuration['extra8']='0';
//extra9
$vehiclemanager_configuration['extra9']='0';
//extra10
$vehiclemanager_configuration['extra10']='0';
$vehiclemanager_configuration['rss']['show']='';
$vehiclemanager_configuration['rss']['registrationlevel']='8';
$vehiclemanager_configuration['wishlist']['show']='1';
$vehiclemanager_configuration['wishlist']['registrationlevel']='-2';
$vehiclemanager_configuration['review_captcha']['show']='1';
$vehiclemanager_configuration['review_captcha']['registrationlevel']='-2';
$vehiclemanager_configuration['contact_captcha']['show']='1';
$vehiclemanager_configuration['contact_captcha']['registrationlevel']='-2';
$vehiclemanager_configuration['booking_captcha']['show']='1';
$vehiclemanager_configuration['booking_captcha']['registrationlevel']='-2';
$vehiclemanager_configuration['add_vehicle_captcha']['show']='1';
$vehiclemanager_configuration['add_vehicle_captcha']['registrationlevel']='-2';
$vehiclemanager_configuration['show_map']['show']='1';
$vehiclemanager_configuration['show_map']['registrationlevel']='-2';
$vehiclemanager_configuration['show_order_by']['show']='1';
$vehiclemanager_configuration['show_order_by']['registrationlevel']='-2';
$vehiclemanager_configuration['owner']['show']='1';
$vehiclemanager_configuration['ownerslist']['show']='0';
$vehiclemanager_configuration['ownerslist']['registrationlevel']='';
$vehiclemanager_configuration['calendar']['show']='1';
$vehiclemanager_configuration['calendarlist']['show']='1';
$vehiclemanager_configuration['calendarlist']['registrationlevel']='-2';
$vehiclemanager_configuration['contactlist']['show']='';
$vehiclemanager_configuration['contactlist']['registrationlevel']='';
$vehiclemanager_configuration['rent_answer']='0';
$vehiclemanager_configuration['buy_answer']='0';
$vehiclemanager_configuration['buy_form']='';
//end rent notify
$vehiclemanager_configuration['rent_before_end_notify']='0';
$vehiclemanager_configuration['rent_before_end_notify_days']='0';
$vehiclemanager_configuration['rent_before_end_notify_email']='';
$vehiclemanager_configuration['calendar']['placeholder']='';
$vehiclemanager_configuration['contact']['placeholder']='';
$vehiclemanager_configuration['featuredmanager']['placeholder']='Safety,Comfort,Multimedia,Other';
$vehiclemanager_configuration['currency']='USD=1;EUR=8.125;RUB=240;';
$vehiclemanager_configuration['allowed_exts']='zip,pdf';
$vehiclemanager_configuration['allowed_exts_img']='jpeg,jpg,png,gif';
$vehiclemanager_configuration['allowed_exts_video']='mp4,ogv,webm';
$vehiclemanager_configuration['allowed_exts_track']='vtt';
$vehiclemanager_configuration['google_openmap']['show']='0';
$vehiclemanager_configuration['api_key']='';
$vehiclemanager_configuration['price_format']='.';
// 1 - affter 0 - beffore
$vehiclemanager_configuration['price_unit_show']='1';
$vehiclemanager_configuration['date_format']='%Y-%m-%d';
$vehiclemanager_configuration['plugin_name_select']='';
$vehiclemanager_configuration['input_link_rent']='default';
$vehiclemanager_configuration['input_link_sale']='default';
$vehiclemanager_configuration['mandatory_year_issue_field_require']='1';
$vehiclemanager_configuration['mandatory_mileage_field_require']='1';
$vehiclemanager_configuration['mandatory_price_field_require']='1';
$vehiclemanager_configuration['search_button']['show']='1';
$vehiclemanager_configuration['search_button']['registrationlevel']='-2';
$vehiclemanager_configuration['rent_request_send_reply_to']['add']='0';
$vehiclemanager_configuration['notification_review_send_reply_to']['add']='';
$vehiclemanager_configuration['vehicle_notification_send_reply_to']['add']='';
$vehiclemanager_configuration['buying_request_notification_send_reply_to']['add']='0';
$vehiclemanager_configuration['keywords_search_show_select']='1';
$vehiclemanager_configuration['search_form_radiuse_range_field_show']='1';
$vehiclemanager_configuration['search_form_radiuse_range']='1000';
$vehiclemanager_configuration['available_for_rent_show_select']='1';
$vehiclemanager_configuration['year_of_issue_show_select']='1';
$vehiclemanager_configuration['price_vehicle_show_select']='1';
$vehiclemanager_configuration['condition_status_show_select']='1';
$vehiclemanager_configuration['listing_status_show_select']='1';
$vehiclemanager_configuration['transmission_type_show_select']='1';
$vehiclemanager_configuration['maker_show_select']='1';
$vehiclemanager_configuration['drive_type_show_select']='1';
$vehiclemanager_configuration['model_show_select']='1';
$vehiclemanager_configuration['number_cylinders_show_select']='1';
$vehiclemanager_configuration['vehicle_type_show_select']='1';
$vehiclemanager_configuration['number_speeds_show_select']='1';
$vehiclemanager_configuration['listing_type_show_select']='1';
$vehiclemanager_configuration['fuel_type_show_select']='1';
$vehiclemanager_configuration['price_type_show_select']='1';
$vehiclemanager_configuration['number_doors_show_select']='1';
$vehiclemanager_configuration['category_show_select']='1';
$vehiclemanager_configuration['vehicleid_show_select']='1';
$vehiclemanager_configuration['comment_show_select']='1';
$vehiclemanager_configuration['title_show_select']='1';
$vehiclemanager_configuration['address_show_select']='1';
$vehiclemanager_configuration['country_show_select']='1';
$vehiclemanager_configuration['region_show_select']='1';
$vehiclemanager_configuration['city_show_select']='1';
$vehiclemanager_configuration['district_show_select']='1';
$vehiclemanager_configuration['zipcode_show_select']='1';
$vehiclemanager_configuration['owner_show_select']='1';
$vehiclemanager_configuration['mileage_show_select']='1';
$vehiclemanager_configuration['contacts_show_select']='1';
$vehiclemanager_configuration['engine_type_show_select']='1';
$vehiclemanager_configuration['city_mpg_show_select']='1';
$vehiclemanager_configuration['highway_mpg_show_select']='1';
$vehiclemanager_configuration['wheelbase_show_select']='1';
$vehiclemanager_configuration['wheeltype_show_select']='1';
$vehiclemanager_configuration['rearaxe_type_show_select']='1';
$vehiclemanager_configuration['brakes_type_show_select']='1';
$vehiclemanager_configuration['exterior_colors_show_select']='1';
$vehiclemanager_configuration['exterior_extras_show_select']='1';
$vehiclemanager_configuration['interior_colors_show_select']='1';
$vehiclemanager_configuration['dashboard_options_show_select']='1';
$vehiclemanager_configuration['interior_extras_show_select']='1';
$vehiclemanager_configuration['safety_options_show_select']='1';
$vehiclemanager_configuration['warranty_options_show_select']='1';
$vehiclemanager_configuration['exactly_show_select']='1';
$vehiclemanager_configuration['search_form_nothing_found_page_show']='1';
$vehiclemanager_configuration['search_form_on_search_page_result_show']='1';
$vehiclemanager_configuration['show_country_region_city_as_text_field']='0';
$vehiclemanager_configuration['default_search_layout']='0';
$vehiclemanager_configuration['order_by_default']='ordering';
$vehiclemanager_configuration['show_vehicle_slider']='1';
$vehiclemanager_configuration['initial_year']= '2020';
$vehiclemanager_configuration['final_year']= '2021';
$vehiclemanager_configuration['extra1_advanced']='3';
$vehiclemanager_configuration['extra2_advanced']='3';
$vehiclemanager_configuration['extra3_advanced']='3';
$vehiclemanager_configuration['extra4_advanced']='3';
$vehiclemanager_configuration['extra5_advanced']='3';
$vehiclemanager_configuration['extra6_advanced']='3';
$vehiclemanager_configuration['extra7_advanced']='3';
$vehiclemanager_configuration['extra8_advanced']='3';
$vehiclemanager_configuration['extra9_advanced']='3';
$vehiclemanager_configuration['extra10_advanced']='3';
//features search options
$vehiclemanager_configuration['search_form_features']['13']='3';
$vehiclemanager_configuration['search_form_features']['12']='3';
$vehiclemanager_configuration['search_form_features']['11']='3';
$vehiclemanager_configuration['search_form_features']['10']='3';
$vehiclemanager_configuration['search_form_features']['9']='3';
$vehiclemanager_configuration['search_form_features']['8']='3';
$vehiclemanager_configuration['search_form_features']['14']='3';
$vehiclemanager_configuration['search_form_features']['15']='3';
$vehiclemanager_configuration['search_form_features']['16']='3';
$vehiclemanager_configuration['search_form_features']['17']='3';
$vehiclemanager_configuration['search_form_features']['18']='3';
$vehiclemanager_configuration['search_form_features']['19']='3';
$vehiclemanager_configuration['search_form_features']['20']='3';
$vehiclemanager_configuration['search_form_features']['21']='3';
$vehiclemanager_configuration['search_form_features']['22']='3';
$vehiclemanager_configuration['search_form_features']['23']='3';
$vehiclemanager_configuration['search_form_features']['24']='3';
$vehiclemanager_configuration['search_form_features']['25']='3';
$vehiclemanager_configuration['search_form_features']['26']='3';
$vehiclemanager_configuration['search_form_features']['27']='3';
$vehiclemanager_configuration['search_form_features']['28']='3';
$vehiclemanager_configuration['search_form_features']['29']='3';
$vehiclemanager_configuration['search_form_features']['30']='3';
$vehiclemanager_configuration['search_form_features']['31']='3';
$vehiclemanager_configuration['search_form_features']['32']='3';
$vehiclemanager_configuration['search_form_features']['33']='3';
$vehiclemanager_configuration['search_form_features']['34']='3';
$vehiclemanager_configuration['search_form_features']['35']='3';
$vehiclemanager_configuration['search_form_features']['36']='3';
$vehiclemanager_configuration['search_form_features']['38']='3';
$vehiclemanager_configuration['search_form_features']['39']='3';
$vehiclemanager_configuration['search_form_features']['40']='3';
$vehiclemanager_configuration['search_form_features']['41']='3';
$vehiclemanager_configuration['search_form_features']['42']='3';
$vehiclemanager_configuration['search_form_features']['43']='3';
$vehiclemanager_configuration['search_form_features']['44']='3';
$vehiclemanager_configuration['search_form_features']['45']='3';
$vehiclemanager_configuration['search_form_features']['46']='3';
$vehiclemanager_configuration['search_form_features']['47']='3';
$vehiclemanager_configuration['search_form_features']['48']='3';
$vehiclemanager_configuration['search_form_features']['49']='3';
$vehiclemanager_configuration['search_form_features']['97']='3';
$vehiclemanager_configuration['search_form_features']['96']='3';
$vehiclemanager_configuration['search_form_features']['95']='3';
$vehiclemanager_configuration['sale_fraction']='1';
$vehiclemanager_configuration['veh_data_columns_lg']='3';
$vehiclemanager_configuration['veh_data_columns_md']='3';
$vehiclemanager_configuration['veh_data_columns_sm']='3';
$vehiclemanager_configuration['veh_data_columns_xs']='2';
$vehiclemanager_configuration['watermark']['show']='0';
$vehiclemanager_configuration['watermark']['type']='text';
$vehiclemanager_configuration['watermark']['file']='';
$vehiclemanager_configuration['watermark']['text']='Watermark';
$vehiclemanager_configuration['watermark']['size']='50';
$vehiclemanager_configuration['watermark']['color']='rgba(255, 255, 255, 0.75)';
$vehiclemanager_configuration['watermark']['angle']='0';
$vehiclemanager_configuration['watermark']['position']='center';
$vehiclemanager_configuration['watermark']['opacity']='60';
$vehiclemanager_configuration['watermark']['min_image_width']='70';
$vehiclemanager_configuration['watermark']['min_image_high']='70';
$vehiclemanager_configuration['category']['ordering']='ordering';
$vehiclemanager_configuration['pdf_print_logo']['show']='1';
$vehiclemanager_configuration['pdf_print_logo_primary_file']['name']='pdf_print_logo.png';
$vehiclemanager_configuration['slider']['height']='56';
$vehiclemanager_configuration['slider']['object_fit']='contain';
?>